DROP TABLE safety.`DEV_POS`;

CREATE TABLE safety.`DEV_POS` 
(`SEQ` BIGINT(20) AUTO_INCREMENT NOT NULL,
`DEV_ID` VARCHAR(36) NOT NULL, 
 `LON` DECIMAL(20,16) NOT NULL, 
 `LAT` DECIMAL(20,16) NOT NULL, 
 `SPD` DECIMAL(20,16) NOT NULL, 
 `BEAR` DECIMAL(20,16) NOT NULL, 
 `CN` NVARCHAR(100) DEFAULT 'N/A', 
 `LOC` NVARCHAR(100) DEFAULT 'N/A', 
 `ADDR` NVARCHAR(300) DEFAULT 'N/A', 
 `DTM` DATETIME NOT NULL, 
 `REG_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
 PRIMARY KEY (`SEQ`)) 
COMMENT = 'save the postion of the device.'
ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE INDEX `DEV_ID_INDEX`
    ON safety.`DEV_POS`(`DEV_ID`);

