DROP TABLE safety.`DEV_POS`;

CREATE TABLE safety.`DEV_POS` 
(`SEQ` BIGINT(20) AUTO_INCREMENT NOT NULL,
`DEV_ID` VARCHAR(36) NOT NULL, 
 `LON` DECIMAL(20,16) NOT NULL, 
 `LAT` DECIMAL(20,16) NOT NULL, 
 `SPD` DECIMAL(20,16) NOT NULL, 
 `BEAR` DECIMAL(20,16) NOT NULL, 
 `CN` NVARCHAR(100) DEFAULT 'N/A', 
 `LOC` NVARCHAR(100) DEFAULT 'N/A', 
 `ADDR` NVARCHAR(300) DEFAULT 'N/A', 
 `DTM` DATETIME NOT NULL, 
 `REG_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
 `GO_ID` VARCHAR(36),
 PRIMARY KEY (`SEQ`)) 
COMMENT = 'save the postion of the device.'
ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE INDEX `DEV_ID_INDEX`
    ON safety.`DEV_POS`(`DEV_ID`);


DROP TABLE safety.`USERS`;

CREATE TABLE safety.`users`
(`_ID` BIGINT(20) AUTO_INCREMENT NOT NULL,
 `EMAIL` VARCHAR(36) NOT NULL,
 `NICK_NAME` VARCHAR(50) NOT NULL,
 `PASSWORD` VARCHAR(120) NOT NULL,
 `MAIL_CONFIRM_YN` VARCHAR(2) DEFAULT 'N',
 `REG_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
 PRIMARY KEY (`_ID`))
COMMENT = 'user info.'
ENGINE=InnoDB DEFAULT CHARSET=utf8;